const CATEGORIES = [
    "AGRICULTURE",
    "BEHAVIOR SCIENCE",
    "BIO & BIOTECH",
    "CHEMISTRY",
    "COMPUTER",
    "ENERGY & TRANSPORT",
    "ENGINEERING",
    "ENVIRONMENTAL",
    "FOOD TECHNOLOGY",
    "MATHEMATICS",
    "PHYSICS",
    "TECH & APPLIED TECH",
    "ROBOTICS"
];
